import { Creative } from "./types";

export const mockCreatives: Creative[] = [
  {
    id: "CR-201",
    product: "Abonnement bien-être",
    creator: "Alice Martin",
    contentType: "UGC vidéo",
    angle: "Social proof",
    hook: "Ils ont testé, ils adorent",
    month: "2024-01",
    status: "actif",
    budgetSpent: 3200,
    conversions: 210,
    estimatedRevenue: 15600,
    roas: 4.9,
    cpa: 15.2,
    impressions: 240000,
    clicks: 12000,
    ctr: 5,
    launchDate: "2024-01-10",
    previewLink: "https://facebook.com",
  },
  {
    id: "CR-178",
    product: "Pack détox",
    creator: "Studio Nova",
    contentType: "Motion design",
    angle: "Résultat avant/après",
    hook: "30 jours pour changer",
    month: "2023-12",
    status: "actif",
    budgetSpent: 2100,
    conversions: 120,
    estimatedRevenue: 7800,
    roas: 3.7,
    cpa: 17.5,
    impressions: 180000,
    clicks: 7600,
    ctr: 4.2,
    launchDate: "2023-12-05",
    previewLink: "https://facebook.com",
  },
  {
    id: "CR-099",
    product: "Café en grain",
    creator: "Louise P.",
    contentType: "Carrousel photo",
    angle: "Artisanat local",
    hook: "Du grain à la tasse",
    month: "2023-11",
    status: "en pause",
    budgetSpent: 950,
    conversions: 40,
    estimatedRevenue: 2600,
    roas: 2.7,
    cpa: 23.7,
    impressions: 88000,
    clicks: 2600,
    ctr: 3,
    launchDate: "2023-11-02",
    previewLink: "https://facebook.com",
  },
];
